### ISSUE TITLE
CT Assertion failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-sampling-distributions#4]
```
projectile-sampling-distributions : phet-io-fuzz : unbuilt : assertSlow
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/projectile-sampling-distributions/projectile-sampling-distributions_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-sampling-distributions%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1735006737763%22%2C%22timestamp%22%3A1735007368646%7D&eall&brand=phet-io&phetioStandalone&fuzz&phetioLogFuzzedValues
ERROR: QUERY: eall&brand=phet-io&phetioStandalone&fuzz&phetioLogFuzzedValues
Uncaught Error: Assertion failed
STACK: Error: Assertion failed
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/assert/js/assert.js:45:21)
    at assertSlow (../../../../../../scenery/js/display/Instance.js:610:8)
    at syncTree (../../../../../../scenery/js/display/Instance.js:712:41)
    at localSyncTree (../../../../../../scenery/js/display/Instance.js:655:11)
    at syncTree (../../../../../../scenery/js/display/Instance.js:712:41)
    at localSyncTree (../../../../../../scenery/js/display/Instance.js:655:11)
    at syncTree (../../../../../../scenery/js/display/Instance.js:712:41)
    at localSyncTree (../../../../../../scenery/js/display/Instance.js:655:11)
    at syncTree (../../../../../../scenery/js/display/Instance.js:712:41)
    at localSyncTree (../../../../../../scenery/js/display/Instance.js:655:11)
    at syncTree (../../../../../../scenery/js/display/Instance.js:712:41)
    at localSyncTree (../../../../../../scenery/js/display/Instance.js:655:11)
    at syncTree (../../../../../../scenery/js/display/Instance.js:712:41)
    at localSyncTree (../../../../../../scenery/js/display/Instance.js:655:11)
    at syncTree (../../../../../../scenery/js/display/Instance.js:712:41)
    at localSyncTree (../../../../../../scenery/js/display/Instance.js:655:11)
    at syncTree (../../../../../../scenery/js/display/Instance.js:712:41)
    at localSyncTree (../../../../../../scenery/js/display/Instance.js:655:11)
    at syncTree (../../../../../../scenery/js/display/Instance.js:571:9)
    at baseSyncTree (../../../../../../scenery/js/display/Display.ts:576:24)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735006737763%2Fprojectile-sampling-distributions%2Fprojectile-sampling-distributions_en.html&simQueryParameters=eall%26brand%3Dphet-io%26phetioStandalone%26fuzz%26phetioLogFuzzedValues&testInfo=%7B%22test%22%3A%5B%22projectile-sampling-distributions%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1735006737763%22%2C%22timestamp%22%3A1735007368646%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735006737763%2Fprojectile-sampling-distributions%2Fprojectile-sampling-distributions_en.html&simQueryParameters=eall%26brand%3Dphet-io%26phetioStandalone%26fuzz%26phetioLogFuzzedValues&testInfo=%7B%22test%22%3A%5B%22projectile-sampling-distributions%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1735006737763%22%2C%22timestamp%22%3A1735007368646%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/projectile-sampling-distributions/projectile-sampling-distributions_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-sampling-distributions%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1735006737763%22%2C%22timestamp%22%3A1735007368646%7D&eall&brand=phet-io&phetioStandalone&fuzz&phetioLogFuzzedValues
[CONSOLE] enabling assert
[CONSOLE] enabling assertSlow
[LOADED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735006737763%2Fprojectile-sampling-distributions%2Fprojectile-sampling-distributions_en.html&simQueryParameters=eall%26brand%3Dphet-io%26phetioStandalone%26fuzz%26phetioLogFuzzedValues&testInfo=%7B%22test%22%3A%5B%22projectile-sampling-distributions%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1735006737763%22%2C%22timestamp%22%3A1735007368646%7D
[CONSOLE] continuous-test-load
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.launcherSection.mysteryLauncherRadioButtonGroup.mysteryLauncher1RadioButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.histogramNode.binControlNode.totalBinsComboBox.listBox.totalBins50Item.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.timeControlNode.speedRadioButtonGroup.fastRadioButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.audioToggleButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.phetButton.phetMenu.fullScreenMenuItem.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.launcherSection.mysteryLauncherRadioButtonGroup.mysteryLauncher1RadioButton.enabledProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.sampleSizeSection.sampleSizeRadioButtonGroup.sampleSize5RadioButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.sampleSizeSection.sampleSizeRadioButtonGroup.sampleSize15RadioButton.enabledProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.expandedProperty: true
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.sampleSelectorNode.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesTabs.overviewTab.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.launcherSection.mysteryLauncherRadioButtonGroup.mysteryLauncher1RadioButton.visibleProperty: true
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.launcherSection.mysteryLauncherRadioButtonGroup.mysteryLauncher6RadioButton.enabledProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.histogramNode.binControlNode.totalBinsComboBox.listBox.totalBins50Item.visibleProperty: true
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.audioPreferencesPanel.launchSoundStrategyControl.radioButtonGroup.noneRadioButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.histogramNode.binControlNode.totalBinsComboBox.listBox.totalBins100Item.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.timeControlNode.selfVisibleProperty: false
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.autoGenerateDataControl.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.sampleSizeSection.sampleSizeRadioButtonGroup.sampleSize5RadioButton.enabledProperty: false
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesTabs.overviewTab.visibleProperty: true
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.sampleSizeSection.sampleSizeRadioButtonGroup.sampleSize5RadioButton.enabledProperty: true
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.autoGenerateDataControl.visibleProperty: true
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.histogramNode.binControlNode.totalBinsComboBox.listBox.totalBins200Item.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.launcherSection.mysteryLauncherRadioButtonGroup.mysteryLauncher1RadioButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.audioPreferencesPanel.launchSoundStrategyControl.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.histogramNode.binControlNode.binWidthComboBox.listBox.binWidth5Item.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.timeControlNode.speedRadioButtonGroup.fastRadioButton.enabledProperty: false
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.phetButton.phetMenu.fullScreenMenuItem.visibleProperty: true
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.timeControlNode.speedRadioButtonGroup.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.thumbnailContainer.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.histogramNode.binControlNode.totalBinsComboBox.listBox.totalBins200Item.visibleProperty: true
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.sampleSelectorNode.visibleProperty: true
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.histogramNode.binControlNode.totalBinsComboBox.listBox.totalBins20Item.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.launcherSection.mysteryLauncherRadioButtonGroup.mysteryLauncher4RadioButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.histogramNode.binControlNode.binWidthComboBox.enabledProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.launcherSection.mysteryLauncherRadioButtonGroup.mysteryLauncher6RadioButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.eraserButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.sampleSelectorNode.incrementButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.singleOrContinuousRadioButtonGroup.selfVisibleProperty: false
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.audioPreferencesPanel.launchSoundStrategyControl.radioButtonGroup.angleRadioButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.timeControlNode.speedRadioButtonGroup.enabledProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.launcherSection.mysteryLauncherRadioButtonGroup.mysteryLauncher2RadioButton.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.general.view.display.supportsPanAndZoomProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.thumbnailContainer.sample40ThumbnailNode.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.expandCollapseButton.enabledProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.expandCollapseButton.enabledProperty: true
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.phetButton.phetMenu.fullScreenMenuItem.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.histogramAccordionBox.histogramNode.barBlockSwitch.enabledProperty: false
[CONSOLE] Assertion failed
[CONSOLE] Debug info: {
  "seed": 0.12234383094560197,
  "currentScreenName": "SamplingScreen",
  "secondsSinceSimStarted": 24.262,
  "simTopLayer": [
    "BarrierRectangle",
    "PopupParentNode: PhetMenu"
  ]
}
[PAGE ERROR] Error: Error: Assertion failed
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/assert/js/assert.js:45:21)
    at Instance.syncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:430:17)
    at Instance.localSyncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:505:48)
    at Instance.syncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:462:18)
    at Instance.localSyncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:505:48)
    at Instance.syncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:462:18)
    at Instance.localSyncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:505:48)
    at Instance.syncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:462:18)
    at Instance.localSyncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:505:48)
    at Instance.syncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:462:18)
    at Instance.localSyncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:505:48)
    at Instance.syncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:462:18)
    at Instance.localSyncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:505:48)
    at Instance.syncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:462:18)
    at Instance.localSyncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:505:48)
    at Instance.syncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:462:18)
    at Instance.localSyncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:505:48)
    at Instance.syncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:462:18)
    at Instance.baseSyncTree (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Instance.js:399:14)
    at SimDisplay.updateDisplay (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/display/Display.js:123:28)
[CONSOLE] continuous-test-error
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.launcherSection.mysteryLauncherRadioButtonGroup.mysteryLauncher1RadioButton.enabledProperty: true
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.visibleProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.launcherSection.mysteryLauncherRadioButtonGroup.mysteryLauncher1RadioButton.visibleProperty: true
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.binStrategyControl.radioButtonGroup.totalBinsRadioButton.enabledProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.sampleSizeSection.sampleSizeRadioButtonGroup.sampleSize15RadioButton.enabledProperty: true
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.phetButton.enabledProperty: false
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.audioPreferencesPanel.launchSoundStrategyControl.radioButtonGroup.noneRadioButton.visibleProperty: true
[CONSOLE] projectileSamplingDistributions.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.binStrategyControl.radioButtonGroup.enabledProperty: false
[CONSOLE] projectileSamplingDistributions.samplingScreen.view.launchPanel.launcherSection.mysteryLauncherRadioButtonGroup.mysteryLauncher3RadioButton.enabledProperty: false

id: "Bayes Node Chrome"
Snapshot from 12/23/2024, 7:18:57 PM
```

**Comment by samreid** [comment]
Probably the same as https://github.com/phetsims/projectile-data-lab/issues/361, let's discuss over there.
